### ISSUE TITLE
Setting "Redirect to 'Internal page or external URL'" to <current> fails

### ISSUE THREAD

**Issue by steve65140** [backdrop-contrib/login_destination#1]
After installing and enabling the Login Destination module I've gone to:
admin/config/people/login-destination/add
Under "Redirect to page | Internal page or external URL" I've set:
<current>
and left everything else to the default values.
When I click the SAVE button I get the error message:
"Incorrect path, Please Enter valid Path"
Help. What have I done wrong?
Screen shot attached.
![login-destination-add-fails](https://cloud.githubusercontent.com/assets/16240249/20259910/945a17f6-aa57-11e6-8003-ecbc1940cd2b.jpg)

**Comment by kleomash** [comment]
Hi!

I fixed it by patching core/includes/path.inc

You should extend checking path in backdrop_valid_path as below:

```
/**
 * Checks a path exists and the current user has access to it.
 *
 * @param $path
 *   The path to check.
 * @param $dynamic_allowed
 *   Whether paths with menu wildcards (like user/%) should be allowed.
 *
 * @return
 *   TRUE if it is a valid path AND the current user has access permission,
 *   FALSE otherwise.
 */
function backdrop_valid_path($path, $dynamic_allowed = FALSE) {
  global $menu_admin;
  // We indicate that a menu administrator is running the menu access check.
  $menu_admin = TRUE;
  if ($path == '<front>' || $path == '<current>' || url_is_external($path)) {
    $item = array('access' => TRUE);
  }
  elseif ($dynamic_allowed && preg_match('/\/\%/', $path)) {
    // Path is dynamic (ie 'user/%'), so check directly against menu_router table.
    if ($item = db_query("SELECT * FROM {menu_router} where path = :path", array(':path' => $path))->fetchAssoc()) {
      $item['link_path']  = $item['path'];
      $item['link_title'] = $item['title'];
      $item['external']   = FALSE;
      $item['options'] = '';
      _menu_link_translate($item);
    }
  }
  else {
    $item = menu_get_item($path);
  }
  $menu_admin = FALSE;
  return $item && $item['access'];
}
```

After that all is worked out.

**Comment by steve65140** [comment]
Many thanks for the fix kleomash, but I gave up on Backdrop as there's no strategy for making multilingual work properly. I've been happily moving all my D7 sites to Kirby CMS.
