### ISSUE TITLE
Rule for authenticated user only applies to all other roles

### ISSUE THREAD

**Issue by argiepiano** [backdrop-contrib/login_destination#11]
If you choose "Authenticated" in "Redirect users with roles" when creating a rule, the result is that ALL users will be redirected. 

While it's true that ALL users are Authenticated users, this is counterintuitive, based on the description of that radio group - the description says "Redirect only the selected role(s). If you select no roles, all users will be redirected.". So in fact choosing "Authenticated" is the same as choosing no role at all.  I haven't checked the D7 version to see if this "works as intended" or if this is a problem with Backdrop's version.

If this is a "works as designed", the it would be desirable to have an option to limit redirection to authenticated users who have no other roles.

**Comment by laryn** [comment]
My understanding would be that "Authenticated" should be different than choosing no role because it would exclude anonymous users -- but I haven't looked at the logic on this in a long time!

EDIT: ha, just remembered what module and action we are discussing here. It's been a long day...

**Comment by laryn** [comment]
I would be interested to know if D7 handles that differently though.

**Comment by argiepiano** [comment]
I've checked the D7 version and it does the same thing. Authenticated user applies basically to all roles. I'll open a feature request for a "NOT" box - that would allow someone to redirect only those who don't have specific roles. 

> My understanding would be that "Authenticated" should be different than choosing no role because it would exclude anonymous user

Yes, but keep in mind that anonymous users don't ever use the log in form! When they do, then they are treated like authenticated ones and are redirected as expected. So the logic here is a bit obscure, since leaving all options unchecked is the same as checking the Authenticated one, unless I'm missing something.

**Comment by laryn** [comment]
@argiepiano It does sound like excluding the authenticated role here might clarify the logic better.
