### ISSUE TITLE
`hook_user_insert()` not ported

### ISSUE THREAD

**Issue by jlfranklin** [backdrop-contrib/login_destination#2]
As an admin with this module enabled, creating a new user returns the following error:

    Warning: Parameter 1 to login_destination_user_insert() expected to be a reference, value given in module_invoke_all()

This is because `login_destination_user_insert()` has the old Drupal 7 [function signature](https://api.drupal.org/api/drupal/modules%21user%21user.api.php/function/hook_user_insert/7.x), not the new backdrop [function signature](https://api.backdropcms.org/api/backdrop/core%21modules%21user%21user.api.php/function/hook_user_insert/1).

**Comment by laryn** [comment]
Thanks @jlfranklin !
