### ISSUE TITLE
One-time login link not redirected

### ISSUE THREAD

**Issue by laryn** [backdrop-contrib/login_destination#3]
I just added this to a site but the user is not redirected on the one-time login link, perhaps because they are taken instead to the reset password page? Ideally after they reset their password they will be redirected.

**Comment by docwilmot** [comment]
Trigger Actions is a contrib module. Maybe that's not a core issue then?

**Comment by laryn** [comment]
@docwilmot Good point -- I just searched this module and don't see that function coming up. I'll remove that from the issue.

**Comment by docwilmot** [comment]
But does it work if you disable Trigger Actions though?

**Comment by laryn** [comment]
Hmm.. I just installed on a separate dev site and without Trigger Actions it does redirect but does not give the Password Reset page first. (The checkbox on Login Destination Settings for "Redirect immediately after using one-time login link. *User will be redirected before given the possibility to change their password*." is not checked).
