### ISSUE TITLE
Merge fixes from Drupal module

### ISSUE THREAD

**Issue by laryn** [backdrop-contrib/login_destination#5]
@jdanthinne I see that there have been other releases of the Drupal module since you ported. Are you interested in merging those into this port and releasing 1.x-1.4?

**Comment by jdanthinne** [comment]
Unfortunately, I haven't worked with Backdrop for almost 2 years (I'm now a Swift iOS dev), and have little (no) time to maintain this module. If you're interested…

**Comment by laryn** [comment]
Ah, I see! Thanks. I'll open an issue to transfer maintainership.
